### ISSUE TITLE
heading levels are broken

### ISSUE THREAD

**Issue by braver** [cjwilburn/atom-language-mediawiki#1]
I think it's supposed to set a class for each heading level, but instead it sets a regex string.

![screen shot 2015-04-13 at 19 38 36](https://cloud.githubusercontent.com/assets/2543659/7121671/6b82f81c-e216-11e4-8eca-4797ab6c2611.png)

**Comment by cjwilburn** [comment]
I found the problematic line and will merge the change in soon. let me know if this helps.
