### ISSUE TITLE
Won't install on Atom 1.40.1 at all

### ISSUE THREAD

**Issue by bernd-wechner** [cjwilburn/atom-language-mediawiki#11]
Just reports "Failed to load language-mediawiki - try again later".

Using this page: https://atom.io/packages/language-mediawiki

and the link it provides is to: atom://settings-view/show-package?package=language-mediawiki

**Comment by maurice-schleussinger** [comment]
Can't confirm this as I just installed the package without problems (Atom v.1.44.0, macOS 10.15.3). Got no console errors and syntax highlighting etc. works.

**Comment by bernd-wechner** [comment]
I just tried to install it again and it worked fine. Then I checked the version and I have 1.28.0 here. Hmmm, so I updated to 1.45.0 and it still works. All good it seems.
