### ISSUE TITLE
Syntax highlight

### ISSUE THREAD

**Issue by marcoshack** [cjwilburn/atom-language-mediawiki#8]
Is this plugin supposed to provide colored syntax highlight as in Markdown? Just installed and a .wiki file just looks like plain text as before (Mediawiki format was detected and selected).

Thanks.
Marcocs

**Comment by Tejeev** [comment]
Same.  Is this package even maintained?

**Comment by cjwilburn** [comment]
@marcoshack This plugin does not currently provide colored synax highlighting or auto-complete. If you have suggestions about what needs to be highlighted, please add suggestions to #5. @Tejeev it hasn't been touched in a while, but I'll make a note of your concern when addressing the other outstanding issues. I'm also open to any pull requests if either of you would like to contribute to this package. Thanks!
